// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLySanPham_EFCore_Chap8.Models;

public partial class DanhMucSanPham
{
    public int Iddm { get; set; }

    public string TenDanhMuc { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<SanPham> SanPhams { get; set; } = new List<SanPham>();

    public DanhMucSanPham()
    {
        SanPhams = new HashSet<SanPham>();
    }
}