// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuanLySanPham_EFCore_Chap8.Models;

public partial class QL_SanPhamContext : DbContext
{
    public QL_SanPhamContext(DbContextOptions<QL_SanPhamContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DanhMucSanPham> DanhMucSanPhams { get; set; }

    public virtual DbSet<SanPham> SanPhams { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DanhMucSanPham>(entity =>
        {
            entity.HasKey(e => e.Iddm).HasName("PK__DanhMucS__9DB7AA9C191906F5");

            entity.ToTable("DanhMucSanPham");

            entity.Property(e => e.Iddm).HasColumnName("iddm");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("create_at");
            entity.Property(e => e.TenDanhMuc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateAt)
                .HasColumnType("datetime")
                .HasColumnName("update_at");
        });

        modelBuilder.Entity<SanPham>(entity =>
        {
            entity.HasKey(e => e.Idsp).HasName("PK__SanPham__9DBB2CF256B07C96");

            entity.ToTable("SanPham");

            entity.Property(e => e.Idsp).HasColumnName("idsp");
            entity.Property(e => e.DonGia)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("don_gia");
            entity.Property(e => e.Dvt)
                .HasMaxLength(20)
                .HasColumnName("dvt");
            entity.Property(e => e.HinhAnh)
                .HasMaxLength(255)
                .HasColumnName("hinh_anh");
            entity.Property(e => e.Iddm).HasColumnName("iddm");
            entity.Property(e => e.Soluong).HasColumnName("soluong");
            entity.Property(e => e.Tensp)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("tensp");

            entity.HasOne(d => d.IddmNavigation).WithMany(p => p.SanPhams)
                .HasForeignKey(d => d.Iddm)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SanPham_DanhMuc");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}