// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLySanPham_EFCore_Chap8.Models;

public partial class SanPham
{
    public int Idsp { get; set; }

    public string Tensp { get; set; }

    public int Soluong { get; set; }

    public string Dvt { get; set; }

    public string HinhAnh { get; set; }

    public decimal DonGia { get; set; }

    public int Iddm { get; set; }

    public virtual DanhMucSanPham IddmNavigation { get; set; }
}